config/routes.rb
Rails.application.routes.draw do
  resources :clientes

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/about'

  resources :productos do
    collection { post :search, to: 'productos#index' }
  end

  
  match '/home', to: 'static_pages#home',  via: 'get'
  match '/help',	to: 'static_pages#help',  via: 'get'
  match '/about',   to: 'static_pages#about',  via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'

  root :to => 'static_pages#home'
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :direccion, :mail)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @search = Producto.search(params[:q])
    @productos = @search.result
    @search.build_condition
    @search.build_sort if @search.sorts.empty?
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :cantidad, :descripcion, :precio)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
end

end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
    

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Lista de clientes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.mail %></td>
        <td><%= link_to 'Show', cliente, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cliente.direccion %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @cliente.mail %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
	By DANIEL Todos los derechos reservados © 2014 :: 
  </small>
  <nav>
	<ul>
  	<li><%= link_to "Créditos", about_path %></li>
  	<li><a href="http://www.MIPAGINA.co/">MYCOMPAÑIA</a></li>
	</ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Guia de Ransack', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "Productos", productos_path %></li>
<li><%= link_to "Clientes", clientes_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workspace" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Workspace" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/productos/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields", class: "btn btn-primary btn-sm" %>
</div>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit  "Guardar", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editar producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto, class: "btn btn-info" %> |
<%= link_to 'Back', productos_path, class: "btn btn-success" %>

app/views/productos/index.html.erb
<center><h1>Listado de productos</h1></center>

<%= search_form_for @search, url: search_productos_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", f, :condition %>
  <div class="actions"><%= f.submit "Search" %></div>
  
  <div class="field">
  Sort:
  <%= f.sort_fields do |s| %>
    <%= s.sort_select %>
  <% end %>
</div>
<% end %>



<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= sort_link(@search, :nombre, "Nombre producto") %></th>
      <th><%= sort_link(@search, :cantidad, "Cantidad") %></th>
      <th><%= sort_link(@search, :descripcion, "Descripcion") %></th>
      <th><%= sort_link(@search, :precio, "Precio") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.cantidad%></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= link_to 'Mostrar', producto, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto), class: "btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Estas Seguro?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path, class: "btn btn-info" %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Atras', productos_path, class: "btn btn-info"%>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @producto.cantidad %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<%= link_to 'Editar', edit_producto_path(@producto), class: "btn btn-info" %> |
<%= link_to 'Atras', productos_path, class: "btn btn-success" %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>